CREATE TABLE staging_events (
  earthquake_id               TEXT       PRIMARY KEY,
  time             TIMESTAMPTZ,
  updated          TIMESTAMPTZ,
  status           TEXT,
  type             TEXT,
  offset_distance  TEXT NOT NULL,
  offset_direction    TEXT             NOT NULL,
  nearest_locality       TEXT             NOT NULL,
  state              TEXT             NOT NULL,
  county             TEXT             NOT NULL,
  region             TEXT             NOT NULL,
  latitude         DOUBLE PRECISION,
  longitude        DOUBLE PRECISION,
  depth            DOUBLE PRECISION,
  depthError       DOUBLE PRECISION,
  horizontalError  DOUBLE PRECISION,
  mag              DOUBLE PRECISION,
  magType          TEXT,
  magError         DOUBLE PRECISION,
  magNst           DOUBLE PRECISION,
  nst              DOUBLE PRECISION,
  gap              DOUBLE PRECISION,
  dmin             DOUBLE PRECISION,
  rms              DOUBLE PRECISION,
  net              TEXT,
  locationSource   TEXT,
  magSource        TEXT
  
);
